### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kioshi** [Mechazawa/FuckFuckAdblock#15]
Hello, i am using uBlock Origin and on webpage http://www.topserialy.sk/serialy/parks-and-recreation-s02e05 (any episode of any serie) fuckfuckadblock doesnt work (i use chrome and tamperedmonkey) http://fuckadblock.sitexw.fr/ show correctly adblock not enabled, but at mentioned page i got notice of adblock instead of video.

Thanks Kioshi.

**Comment by Mechazawa** [comment]
They don't seem to use FuckFuckAdblock and instead made their own thing. Whitelisting `/js/adnetwork.js` should do the trick.

``` html
<!--Adblock Check--> 
<script type="text/javascript" src="/js/adnetwork.js"></script> 
<script type="text/javascript"> 
jQuery(document).ready(checkAds());

function checkAds() {
    if (document.getElementById('ad-etarget') != undefined) {
        document.write("<script>_gaq.push(['_trackEvent', 'Adblock', 'Unblocked', 'false',,true]);</sc" + "ript>");
    } else {
        document.write("<script>_gaq.push(['_trackEvent', 'Adblock', 'Blocked', 'true',,true]);</sc" + "ript>");
    }
}
</script> 
<!--End Adblock Check-->
```

**Comment by Kioshi** [comment]
Oh, thanks i will do that.
