### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by jachymb** [Mechazawa/FuckFuckAdblock#16]
on this url http://news.nationalgeographic.com/2016/03/160331-car-parts-plastics-dead-whales-germany-animals/

**Comment by Mechazawa** [comment]
It does not look like `news.nationalgeographic.com` uses FuckAdBlock.js and it thus not supported.

> A simple userscript that acts like FuckAdBlock.js (A well known adblock detector) but always says that no adblock was detected.
