### ISSUE TITLE
Does not work on moonbitco.in

### ISSUE THREAD

**Issue by Evanito** [Mechazawa/FuckFuckAdblock#20]
First off, simply doesn't work normally. 

And then when I disable adblock, it creates instances over and over (I see the tampermonkey script count increasing.)

These are both bugs.

**Comment by WaKeMaTTa** [comment]
It works for me on http://moonbit.co.in/

**Comment by Mechazawa** [comment]
This repo is just a reference implimentation of a technique to counter FuckAdBlock.js. It doesn't look like http://moonbit.co.in is using FuckadBlock.js and is thus not supported.
