### ISSUE TITLE
Doesn't work on forbes.com

### ISSUE THREAD

**Issue by anton-hrytsevich** [Mechazawa/FuckFuckAdblock#22]
OS Ubuntu 15.04 - 64, chrome 50.0.2661.94 (64-bit), run script under Tampermonkey v4.0.25. Adblock - [uBlock](https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn).

Site still know that I use adblock.

**Comment by akinnee** [comment]
It's working on Forbes.com for me on Chrome on Windows 10.

**Comment by Mechazawa** [comment]
Forbes doesn't use FuckAdblock. This repo is just an implementation for bypassing one specific anti-adblocker. 

```
>> window.location.toString()
<< "http://www.forbes.com/home_europe/"
>> window.fuckAdblock
<< undefined
```

**Comment by anton-hrytsevich** [comment]
@Mechazawa, ok. thank you.
