### ISSUE TITLE
Not working on some sites

### ISSUE THREAD

**Issue by 5Strogino** [Mechazawa/FuckFuckAdblock#5]
1. rutube.ru
   Watch any video
   Example: http://rutube.ru/video/0f7f9925061178578cadfa2199eb3ec2/?ref=search
2. https://chekalskiy.ru/adblock-detection/
   To detect AdBlock (even using FuckFuckAdBlock) add script advert.js and write some code with ad patterns.

**Comment by SERVCUBED** [comment]
The first site uses the class name 'blockAdBlock' instead of 'FuckAdBlock,' which causes this script to not work. 

The second site doesn't use FuckAdBlock. It uses a script with the URL https://chekalskiy.ru/adblock-detection/advert.js to set a variable to show an adblocker isn't enabled. Most adblockers block this URL because it contains the word 'advert.'

**Comment by CptSpaceToaster** [comment]
Installed locally: 

## ![scripts](http://i.imgur.com/WgAkxZ3.png)

Still detected here: http://fuckadblock.sitexw.fr/
![scripts](http://i.imgur.com/knmjf01.png)

Would you rather continue this issue?  or start anew?

**Comment by Mechazawa** [comment]
Try installing it using [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)

**Comment by CptSpaceToaster** [comment]
I installed via Tampermonkey, it now functions as expected.

**Comment by Mechazawa** [comment]
@5Strogino How was the userscript installed? Using Tampermonkey or Greasemonkey?

**Comment by Mechazawa** [comment]
It doesn't seem like the first link uses `fuckadblock.js`. The second link does not seem to be using fuckfuckadblock.js either. Try whitelisting their `advert.js`.

**Comment by 5Strogino** [comment]
Yeah. I used this script via Tampermonkey.
So. I though that script is more powerful and can be used on different sites. I did not know what this script only avoids his brother FuckAdBlock script and nothing else.

**Comment by Mechazawa** [comment]
> A simple userscript that acts like FuckAdBlock.js (A well known adblock detector) but always says that no adblock was detected.
