### ISSUE TITLE
Doesn't work on imgpuppy.com

### ISSUE THREAD

**Issue by vikstrous** [Mechazawa/FuckFuckAdblock#8]
I know this is not meant to be a general purpose anti-anti-adblocking script, but it would be great to add support for whatever these guys are using. Example:

http://www.imgpuppy.com/image/bcrT

Alternatively, can you point me to a general purpose anti-anti-adblocking tool?

**Comment by Mechazawa** [comment]
FuckFuckAdblock only blocks adblock detection using fuckadblock
